# 3-6 More Guests: You just found a bigger dinner table, so now more space is available. Think of three more guests to invite to dinner. Start with your program from Exercise 3-4 or Exercise 3-5. Add a print statement to the end of your program informing people that you found a bigger dinner table. Then use insert() to add one new guest to the beginning of your list, use insert() to add one new guest to the middle of your list, and use append() to add one new guest to the end of your list. Finally, print a new set of invitation messages, one for each person in your list.
invited = ["Furina", 'King', 'Euclid', 'Euler']
print(f'Hello, {invited[0]}, you are invited to dinner!')
print(f'Hello, {invited[-3]}, you are invited to dinner!')
print(f'Hello, {invited[2]}, you are invited to dinner!')
print(f'Hello, {invited[-1]}, you are invited to dinner!')
print(f"Oh, due to some issue, {invited[2]} can't make it for the dinner today")
invited.pop(2)
invited.insert(2, 'Denia')
print('The new set of invitation letters are...')
print(f'Hello, {invited[0]}, you are invited to dinner!')
print(f'Hello, {invited[-3]}, you are invited to dinner!')
print(f'Hello, {invited[2]}, you are invited to dinner!')
print(f'Hello, {invited[-1]}, you are invited to dinner!')
print("Good News, everyone, I just found a bigger table, so we are going to have a bigger party now")
invited.insert(0, 'Chisa')
invited.insert(2, "Focalors")
invited.append('Ayaka')
print("The updated set of invitation letters are...")
print(f'Hello, {invited[0]}, you are invited to dinner!')
print(f'Hello, {invited[-6]}, you are invited to dinner!')
print(f'Hello, {invited[2]}, you are invited to dinner!')
print(f'Hello, {invited[3]}, you are invited to dinner!')
print(f'Hello, {invited[-3]}, you are invited to dinner!')
print(f'Hello, {invited[5]}, you are invited to dinner!')
print(f'Hello, {invited[-1]}, you are invited to dinner!')