# 2-10 Every Function: Think of something you could store in a list. Write a program that creates a list containing these items and then uses each function introduced in this chapter at least once.
games = ['sudoku', 'chess', 'wuwa', 'tetris', 'osu!']
print(games)
print(games[2].title())
print(f'My favorite game is {games[-1].title()}.')
games[2] = 'genshin'
print(games)
games.append('hsr')
print(games)
games.insert(2, 'wuwa')
print(games)
del games[-2]
print(games)
popped_game = games.pop()
print(games)
print(popped_game)
popped_game = games.pop(1)
print(games)
print(popped_game)
games.remove("genshin")
print(games)
worst_game = 'tetris'
games.remove(worst_game)
print(games)
print(f"The worst game is {worst_game.title()}.")
games.append(worst_game)
games.append('ludo')
games.insert(0, 'monopoly')
print(games)
print(sorted(games))
print(sorted(games, reverse=True))
print(games)
games.reverse()
print(games)
games.reverse()
print(games)
games.sort()
print(games)
games.sort(reverse=True)
print(games)
length = len(games)
print(f'The number of games I have is {length}.')